"""Add issue_type to issue_reports

Revision ID: f238347409d7
Revises: 992216136ae5
Create Date: 2024-10-17 04:03:47.791519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f238347409d7'
down_revision = '992216136ae5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issue_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('issue_type', sa.Enum('Hardware', 'Software', 'Both', name='issuetype'), nullable=False))
        batch_op.add_column(sa.Column('software', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issue_reports', schema=None) as batch_op:
        batch_op.drop_column('software')
        batch_op.drop_column('issue_type')

    # ### end Alembic commands ###
